language: generic

cache:
  directories:
    - mame

arch: arm64

git:
  depth: false

dist: bionic

services:
  - docker

before_install:
  - apt-get update -qq
  - apt-get install -y  libsdl2-dev libasound2 qtbase5-dev
  - git clone --depth 1 --branch mame0235 https://github.com/mamedev/mame.git
  
script:
  - cd mame
  - make SUBTARGET=arcade
